---
image: docker:///cloudfoundry/diego-ci

paths:
  stager: gopath/src/github.com/cloudfoundry-incubator/stager

run:
  path: gopath/src/github.com/cloudfoundry-incubator/stager/scripts/concourse-test
